fastlane for F-Droid
hschueh/oh_tai_gi pull request #3
Opened 2022-07-16 06:31 UTC by linsui

I'm not familiar with Traditional Chinese so I didn't add zh-TW locale. I thought it makes sense since this is a Taiwanese learning app. It would be great if you can help. Thanks!

2022-07-16 06:40 UTC, hschueh requested changes
One small request 👍  I guess you mean I can add the zh-TW by myself?

2022-07-16 06:40 UTC, hschueh commented on fastlane/metadata/android/en-US/full_description.txt
> +<li>Reviewing words with flaping card game</li>
typo: `flipping cards` or `card flipping`

2022-07-16 06:44 UTC, linsui commented
Yes! I'm not familiar that so I can't do that myself.

2022-07-16 06:46 UTC, linsui commented on fastlane/metadata/android/en-US/full_description.txt
> +<li>Reviewing words with flaping card game</li>
Fixed!

2022-07-16 06:46 UTC, hschueh approved these changes
LGTM!

2022-07-16 07:08 UTC, hschueh commented
> Yes! I'm not familiar that so I can't do that myself.

Done!

2022-07-16 08:35 UTC, linsui commented
Thanks!

2022-07-16 08:36 UTC, merged

2022-07-19 17:54 UTC, hschueh commented
> Yes! I'm not familiar that so I can't do that myself.

@linsui Sorry for the question. I found that the copy for zhTW is simplified Chinese on [F-Droid](https://f-droid.org/packages/com.gonnaggstudio.oh_tai_gi/). 
Did I make any mistake with my metadata?

2022-07-20 01:59 UTC, linsui commented
It seems it's a bug of the website. In the client the metadata is displayed in the correct locale. I'll report the problem. Thanks!